### ISSUE TITLE
LMDB Auto Grow Issue

### ISSUE THREAD

**Issue by Philipp-p** [eclipse-rdf4j/rdf4j#4547] opened 2023-05-15 09:06 UTC
### Current Behavior

Please take a look at the repo I created for this issue https://github.com/Philipp-p/RDF4J.auto.grow.issue. It sadly features some additional code to convert an IFC File to a RDF model as otherwise the repo, that is already at the file limit without git-LFS, would be inconvenient to handle. It can be completely ignored, all relevant code is located in Application.java and RepositoryUtils.java 

The Application will convert a rather large IFC file and add it to the repository. Afterwards the context will be deleted and the same model added again to the repository. This will fail during the commit of the second transaction with the an error message, see dedicated repo.

### Expected Behavior

The Application should convert a rather large IFC file to and RDF model and commit it to the RDF4J repository. Afterwards that the context wil be deleted and the same model will be added to the repository. This should work without any issues.

### Steps To Reproduce

Please see https://github.com/Philipp-p/RDF4J.auto.grow.issue

### Version

4.2.3

### Are you interested in contributing a solution yourself?

Perhaps?

### Anything else?

Error messages and everything else is located at the dedicated repo.

**Comment by kenwenzel** [comment] 2023-05-15 13:54
I've modified the code a bit to run the tests locally and without loading the whole RDF file into memory:
https://github.com/kenwenzel/RDF4J.auto.grow.issue

Even the second transaction commits with this version.

Do you have a longer stack trace that shows where the actual exception is thrown?

**Comment by Philipp-p** [comment] 2023-05-15 16:21
The setup with the container and the byte array was taken from my actual software project I'm working on that runs on a server, that's why I handled it this way. The container though, I thought is better to keep in the setup, because how knows maybe that's the issue all along.

I modified my demo repo to handle the conversion according to your suggestion, to only convert it once and then hand it over as a file. On my laptop if I run it locally or with a container the issue remains the same, sadly I have no access to the more powerful workstations and server right now to test that. I will however do that later and give an update accordantly, but I expect no change in behaviour as from my experimentation below.

Something I noticed playing around with your fork and mine, is that everything runs smoothly and completes without issues, even on my Laptop (local and with container), if I adapt another change from you. I have to change the transactions to  ```IsolationLevels.NONE``` and then there are no issues at all. Beside really speeding things up, this would have some unwelcome side effects regarding the transaction visibility and the possible lack of the possibility to rollback a transaction according to the documentation [(link)](https://rdf4j.org/javadoc/4.2.3/org/eclipse/rdf4j/common/transaction/IsolationLevels.html) . If I try your fork with the removed ```IsolationLevels.NONE```, the error is the same as with the containerised version under Linux (see the stack trace below). If you try to run this for yourself, be warned about the runtime. Your version runs on my laptop for around 2-4 min und the version without ```IsolationLevels.NONE``` ran for around 50 min.

Regarding longer stack traces, I sadly can only offer you the ones in the repo, the main exception being: ```org.eclipse.rdf4j.repository.RepositoryException: Transaction handling error: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached```

But I can give you the stack trace of your fork when the ```IsolationLevels.NONE``` is removed (failing at second commit, same as container version):
```java
ERROR [main] (LmdbSailStore.java:461) - Encountered an unexpected problem while trying to commit
java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached
	at org.eclipse.rdf4j.sail.lmdb.LmdbUtil.E(LmdbUtil.java:61)
	at org.eclipse.rdf4j.sail.lmdb.TripleStore.endTransaction(TripleStore.java:863)
	at org.eclipse.rdf4j.sail.lmdb.TripleStore.commit(TripleStore.java:901)
	at org.eclipse.rdf4j.sail.lmdb.LmdbSailStore$LmdbSailSink.flush(LmdbSailStore.java:451)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.flush(SailSourceBranch.java:300)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.autoFlush(SailSourceBranch.java:392)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch$1.close(SailSourceBranch.java:197)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.flush(SailSourceBranch.java:303)
	at org.eclipse.rdf4j.sail.base.UnionSailSource.flush(UnionSailSource.java:74)
	at org.eclipse.rdf4j.sail.base.SailSourceConnection.commitInternal(SailSourceConnection.java:471)
	at org.eclipse.rdf4j.sail.lmdb.LmdbStoreConnection.commitInternal(LmdbStoreConnection.java:86)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.commit(AbstractSailConnection.java:496)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:218)
	at demo.Application.main(Application.java:86)
 WARN [main] (AbstractSailConnection.java:272) - Rolling back transaction due to connection close
org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:220)
	at demo.Application.main(Application.java:86)
Caused by: org.eclipse.rdf4j.sail.SailException: java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached
	at org.eclipse.rdf4j.sail.lmdb.LmdbSailStore$LmdbSailSink.flush(LmdbSailStore.java:462)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.flush(SailSourceBranch.java:300)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.autoFlush(SailSourceBranch.java:392)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch$1.close(SailSourceBranch.java:197)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.flush(SailSourceBranch.java:303)
	at org.eclipse.rdf4j.sail.base.UnionSailSource.flush(UnionSailSource.java:74)
	at org.eclipse.rdf4j.sail.base.SailSourceConnection.commitInternal(SailSourceConnection.java:471)
	at org.eclipse.rdf4j.sail.lmdb.LmdbStoreConnection.commitInternal(LmdbStoreConnection.java:86)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.commit(AbstractSailConnection.java:496)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:218)
	... 1 more
Caused by: java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached
	at org.eclipse.rdf4j.sail.lmdb.LmdbUtil.E(LmdbUtil.java:61)
	at org.eclipse.rdf4j.sail.lmdb.TripleStore.endTransaction(TripleStore.java:863)
	at org.eclipse.rdf4j.sail.lmdb.TripleStore.commit(TripleStore.java:901)
	at org.eclipse.rdf4j.sail.lmdb.LmdbSailStore$LmdbSailSink.flush(LmdbSailStore.java:451)
	... 10 more
Exception in thread "main" java.lang.RuntimeException: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached
	at demo.Application.main(Application.java:96)
Caused by: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:220)
	at demo.Application.main(Application.java:86)
Caused by: org.eclipse.rdf4j.sail.SailException: java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached
	at org.eclipse.rdf4j.sail.lmdb.LmdbSailStore$LmdbSailSink.flush(LmdbSailStore.java:462)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.flush(SailSourceBranch.java:300)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.autoFlush(SailSourceBranch.java:392)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch$1.close(SailSourceBranch.java:197)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.flush(SailSourceBranch.java:303)
	at org.eclipse.rdf4j.sail.base.UnionSailSource.flush(UnionSailSource.java:74)
	at org.eclipse.rdf4j.sail.base.SailSourceConnection.commitInternal(SailSourceConnection.java:471)
	at org.eclipse.rdf4j.sail.lmdb.LmdbStoreConnection.commitInternal(LmdbStoreConnection.java:86)
	at org.eclipse.rdf4j.sail.helpers.AbstractSailConnection.commit(AbstractSailConnection.java:496)
	at org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.commit(SailRepositoryConnection.java:218)
	... 1 more
Caused by: java.io.IOException: MDB_MAP_FULL: Environment mapsize limit reached
	at org.eclipse.rdf4j.sail.lmdb.LmdbUtil.E(LmdbUtil.java:61)
	at org.eclipse.rdf4j.sail.lmdb.TripleStore.endTransaction(TripleStore.java:863)
	at org.eclipse.rdf4j.sail.lmdb.TripleStore.commit(TripleStore.java:901)
	at org.eclipse.rdf4j.sail.lmdb.LmdbSailStore$LmdbSailSink.flush(LmdbSailStore.java:451)
	... 10 more
```

**Comment by kenwenzel** [comment] 2023-05-16 06:17
Thank you for the trace.
I think it should be easy to fix this. We just need to grow the database more (at least 2 pages) at this point:
https://github.com/eclipse/rdf4j/blob/39a07105167201124c75bb9decc9749a143cc7e7/core/sail/lmdb/src/main/java/org/eclipse/rdf4j/sail/lmdb/TripleStore.java#L822

Regarding the performance issue with the default isolation level: This seems to be related to https://github.com/eclipse/rdf4j/issues/2998

**Comment by Philipp-p** [comment] 2023-05-16 11:16
That sounds like the root issue here. I just noticed that it was actually you that implemented the auto grow with #3650. I'm still a bit puzzled why this issue only happens with the default isolation level, but I probably just didn't dig deep enough into the code base…

I think you are right, the performance issue with the default isolation level seems exactly to be issue #2998.

Thanks for your time and help!

**Comment by hmottestad** [comment] 2023-05-16 12:06
There might be a difference between what happens when adding data with NONE directly vs. how the overflow model flushes.

Could be as simple as the flushing from the overflow model somehow bypassing the auto grow code. Is there any logging to show what the auto grow code does? Or maybe we could add some, since it might be useful anyways.

**Comment by kenwenzel** [comment] 2023-05-16 12:12
@hmottestad Thank you for this hint. I'll investigate this.

**Comment by kenwenzel** [comment] 2023-05-21 08:08
This discussion might be related: https://forge.univention.org/bugzilla/show_bug.cgi?id=50114#c5
Do you have any parallel connections open for reading data while running the insertion process?

Caffe also encountered this problem: https://github.com/BVLC/caffe/issues/4108

I am not yet sure if this is simple to fix.

The autogrow feature stops inserting data if less than 512kB are available within the LMDB database and overflows data to a secondary database. In theory this should ensure that we have more than 120 free 4kB pages available for committing the current transaction.

**Comment by Philipp-p** [comment] 2023-05-22 08:38
> This discussion might be related: https://forge.univention.org/bugzilla/show_bug.cgi?id=50114#c5 Do you have any parallel connections open for reading data while running the insertion process?

No, I didn't have any open while generating the output from the demo and I discovered this issues also while having no concurrent transactions running. The project I'm working on sadly needs this ability to run concurrent transactions though.

**Comment by kenwenzel** [comment] 2023-05-22 11:38
OK, I think that the management of stale transactions in combination with the current implementation of Changeset may had an influence on this. Although I can't reproduce the bug in other situations the related PR in combination with the planned changes to Changeset should fix the problem.

**Comment by Philipp-p** [comment] 2023-05-22 11:41
That sounds great! Thanks for all your work and help!

**Comment by kenwenzel** [comment] 2023-05-22 11:45
You're welcome.

BTW, meanwhile you can safely use `IsolationLevels.NONE` as LmdbStore has native support for transactions and will isolate all readers from seeing the changes until the transaction is committed.

**Closed** 2023-10-17 13:32 UTC
Labels: 🐞 bug, M1, LMDB
